services:
    personal-website:
        build: .
        container_name: personal-website
        restart: unless-stopped
        networks:
            - web

# Used by Caddy in the homelab config
networks:
    web:
        name: web
        external: true
