services:
    personal-website:
        build: .
        container_name: personal-website
        restart: unless-stopped
        environment:
            - PRIVATE_PASSWORD=${PRIVATE_PASSWORD}
        networks:
            - web

networks:
    web:
        name: web
        external: true
